apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: 'vikrantsundriyal/utilsflask'
    newTag: 'v002'
replicas:
  - name: flask-deployment
    count: 2
